language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
    - website/node_modules
    - website/public

jobs:
  include:
    - stage: Code check
      name: Linting
      script: npm run lint

    - stage: Code check
      name: Type checking
      script: npm run test:types

    - stage: Tests
      name: DOM tests
      script: npm run test:dom

    - stage: Tests
      name: Functional tests
      script: npm run test:functional

    - stage: Deploy docs
      if: branch = master
      node_js: 12
      before_install:
        - cd website
        - source ./scripts/should-deploy-docs.sh
      script: npm run build:ci
      deploy:
        # https://docs.travis-ci.com/user/deployment/pages/
        provider: pages
        local_dir: website/public
        target_branch: gh-pages
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
